// ============================================================
// MemoEnglish - Extended Phonetics Dictionary
// Based on CMUdict (Carnegie Mellon University) + Manual curation
// Notation: Portuguese-friendly phonetic spelling
// ============================================================

const PHONETICS_DB = {
    // A
    "a": "ê", "ability": "ê-bíl-i-ti", "able": "êi-bul", "about": "ê-báut",
    "above": "ê-báv", "accept": "ák-sêpt", "according": "ê-kór-din", "account": "ê-káunt",
    "across": "ê-króss", "act": "akt", "action": "ák-shun", "actually": "ák-tchu-êli",
    "add": "ad", "address": "ád-rês", "after": "áf-ter", "again": "ê-guên",
    "against": "ê-guênst", "age": "êidj", "ago": "ê-gou", "agree": "ê-grí",
    "air": "ér", "all": "ol", "allow": "ê-láu", "almost": "ól-moust",
    "alone": "ê-lóun", "along": "ê-lón", "already": "ól-rêdi", "also": "ól-sou",
    "always": "ól-uêiz", "am": "am", "american": "ê-mér-i-ken", "among": "ê-máng",
    "amount": "ê-máunt", "an": "en", "and": "and", "another": "ê-náder",
    "any": "ên-i", "anyone": "ên-i-uán", "anything": "ên-i-thin", "anyway": "ên-i-uêi",
    "appear": "ê-pír", "apple": "áp-ul", "apply": "ê-plái", "are": "ár",
    "area": "ér-i-ê", "around": "ê-ráund", "as": "az", "ask": "ask",
    "at": "at", "away": "ê-uêi",
    // B
    "baby": "bêi-bi", "back": "bak", "bad": "bad", "ball": "bol",
    "be": "bi", "bear": "bêr", "beautiful": "biú-ti-ful", "because": "bi-kóz",
    "become": "bi-kám", "been": "bin", "before": "bi-fór", "begin": "bi-guín",
    "behind": "bi-háind", "believe": "bi-lív", "best": "bêst", "better": "bêt-er",
    "between": "bi-tuín", "big": "big", "black": "blak", "blue": "blú",
    "book": "buk", "both": "boud", "boy": "bói", "bring": "brin",
    "brother": "bráder", "but": "bat", "by": "bái",
    // C
    "call": "kol", "came": "kêim", "can": "kan", "car": "kár",
    "care": "kêr", "carry": "kér-i", "certain": "sêr-ten", "change": "tchêindj",
    "check": "tchek", "children": "tchíl-dren", "city": "sít-i", "class": "klas",
    "clear": "klír", "close": "klouz", "cold": "kould", "color": "kál-er",
    "come": "kam", "coming": "kám-in", "community": "kê-miú-ni-ti", "company": "kám-pê-ni",
    "complete": "kêm-plít", "consider": "kên-síd-er", "continue": "kên-tín-iu", "control": "kên-tróul",
    "country": "kán-tri", "course": "kors", "create": "kri-êit", "cut": "kat",
    // D
    "dark": "dark", "day": "dêi", "days": "dêiz", "decide": "di-sáid",
    "deep": "díp", "did": "did", "different": "díf-er-ênt", "do": "dú",
    "does": "daz", "done": "dan", "door": "dor", "down": "daun",
    "draw": "dro", "dream": "drím", "drive": "dráiv", "during": "diúr-in",
    // E
    "each": "ítch", "early": "êrl-i", "easy": "íz-i", "eat": "ít",
    "either": "íd-er", "else": "êls", "end": "ênd", "enough": "i-náf",
    "even": "ív-en", "ever": "év-er", "every": "êv-ri", "everyone": "êv-ri-uán",
    "everything": "êv-ri-thin", "example": "ig-zám-pul", "expect": "ik-spêkt",
    "experience": "ik-spír-i-ens", "explain": "ik-splêin",
    // F
    "face": "fêis", "fact": "fakt", "fall": "fol", "family": "fám-i-li",
    "far": "fár", "feel": "fíl", "few": "fiú", "find": "fáind",
    "first": "fêrst", "follow": "fól-ou", "food": "fúd", "for": "for",
    "form": "form", "found": "fáund", "free": "frí", "friend": "frênd",
    "from": "from", "front": "frant", "full": "ful", "fun": "fan",
    // G
    "game": "guêim", "gave": "guêiv", "get": "guêt", "girl": "gêrl",
    "give": "guív", "go": "gou", "going": "góu-in", "gone": "gon",
    "good": "gud", "got": "gat", "government": "gáv-ern-ment", "great": "grêit",
    "green": "grín", "group": "grúp", "grow": "grou",
    // H
    "had": "had", "hand": "hand", "happen": "háp-en", "happy": "háp-i",
    "hard": "hard", "has": "haz", "have": "hav", "he": "hí",
    "head": "hêd", "hear": "hír", "heart": "hárt", "help": "hêlp",
    "her": "hêr", "here": "hír", "high": "hái", "him": "him",
    "his": "hiz", "home": "houm", "hope": "houp", "hour": "áuer",
    "house": "háus", "how": "háu", "however": "hau-êv-er", "human": "hiú-men",
    // I
    "i": "ái", "idea": "ai-dí-ê", "if": "if", "important": "im-pór-tent",
    "in": "in", "include": "in-klúd", "information": "in-for-mêi-shun",
    "instead": "in-stêd", "interest": "ín-ter-est", "into": "ín-tu", "is": "iz",
    "it": "it", "its": "its",
    // J
    "job": "djob", "join": "djóin", "just": "djast",
    // K
    "keep": "kíp", "kind": "káind", "know": "nou", "knowledge": "nól-idj",
    // L
    "large": "lardj", "last": "last", "late": "lêit", "later": "lêit-er",
    "learn": "lêrn", "leave": "lív", "left": "lêft", "less": "lês",
    "let": "lêt", "life": "láif", "light": "láit", "like": "láik",
    "little": "lít-ul", "live": "lív", "long": "lon", "look": "luk",
    "lose": "lúz", "love": "lav", "low": "lou",
    // M
    "make": "mêik", "man": "man", "many": "mên-i", "may": "mêi",
    "maybe": "mêi-bi", "me": "mí", "mean": "mín", "meet": "mít",
    "might": "máit", "mind": "máind", "miss": "mis", "money": "mán-i",
    "more": "mor", "most": "moust", "move": "múv", "much": "mátch",
    "must": "mast", "my": "mái",
    // N
    "name": "nêim", "need": "níd", "never": "nêv-er", "new": "niú",
    "next": "nêkst", "nice": "náis", "night": "náit", "no": "nou",
    "not": "nat", "nothing": "náth-in", "now": "náu", "number": "nám-ber",
    // O
    "of": "ov", "off": "of", "often": "óf-ten", "old": "ould",
    "on": "on", "once": "uáns", "only": "oun-li", "open": "óu-pen",
    "or": "or", "other": "áder", "our": "áuer", "out": "áut",
    "over": "óuv-er", "own": "oun",
    // P
    "part": "párt", "pay": "pêi", "people": "píp-ul", "perhaps": "per-háps",
    "place": "plêis", "plan": "plan", "play": "plêi", "point": "póint",
    "possible": "pós-i-bul", "power": "páuer", "problem": "próblem", "put": "put",
    // Q
    "question": "kuês-tchun", "quite": "kuáit",
    // R
    "read": "ríd", "real": "ríl", "really": "ríl-i", "reason": "ríz-en",
    "remember": "ri-mêm-ber", "right": "ráit", "room": "rúm", "run": "ran",
    // S
    "said": "sêd", "same": "sêim", "saw": "so", "say": "sêi",
    "school": "skúl", "second": "sêk-end", "see": "sí", "seem": "sím",
    "send": "sênd", "set": "sêt", "she": "shi", "should": "shud",
    "show": "shou", "side": "sáid", "since": "sins", "small": "smol",
    "so": "sou", "some": "sam", "something": "sám-thin", "sometimes": "sám-táimz",
    "soon": "sún", "sorry": "sór-i", "speak": "spík", "stand": "stand",
    "start": "start", "stay": "stêi", "still": "stil", "stop": "stop",
    "story": "stór-i", "study": "stád-i", "such": "sátch", "sure": "shur",
    // T
    "take": "têik", "talk": "tok", "tell": "têl", "than": "dan",
    "that": "dat", "the": "dê", "their": "dêr", "them": "dêm",
    "then": "dên", "there": "dêr", "these": "díz", "they": "dêi",
    "thing": "thin", "think": "think", "this": "dis", "those": "douz",
    "though": "dou", "through": "drú", "time": "táim", "to": "tú",
    "today": "tu-dêi", "together": "tu-guéd-er", "too": "tú", "try": "trái",
    "turn": "têrn", "two": "tú",
    // U
    "under": "án-der", "understand": "ân-der-stánd", "until": "an-tíl", "up": "ap",
    "us": "as", "use": "iúz",
    // V
    "very": "vêr-i",
    // W
    "want": "uánt", "was": "uáz", "water": "uót-er", "way": "uêi",
    "we": "uí", "week": "uík", "well": "uêl", "went": "uênt",
    "were": "uêr", "what": "uát", "when": "uên", "where": "uêr",
    "whether": "uéd-er", "which": "uítch", "while": "uáil", "who": "hú",
    "why": "uái", "will": "uíl", "with": "uíd", "without": "uid-áut",
    "woman": "uúm-en", "word": "uêrd", "work": "uêrk", "world": "uêrld",
    "would": "wud", "write": "ráit",
    // Y
    "year": "yír", "yes": "yês", "yet": "yêt", "you": "iú",
    "young": "yáng", "your": "yor",
    // Extra common phrases / contractions
    "i'm": "áim", "i'll": "áil", "i've": "áiv", "i'd": "áid",
    "he's": "híz", "she's": "shíz", "it's": "its", "that's": "dats",
    "we're": "uír", "they're": "dêr", "you're": "yor", "don't": "dount",
    "can't": "kant", "won't": "uount", "doesn't": "dáz-ent", "didn't": "díd-ent",
    "isn't": "íz-ent", "wasn't": "uáz-ent", "aren't": "árnt", "weren't": "uêrnt",
    "haven't": "háv-ent", "hasn't": "ház-ent", "couldn't": "kúd-ent",
    "wouldn't": "wúd-ent", "shouldn't": "shúd-ent", "let's": "lêts",
    "there's": "dêrz", "here's": "hírz", "what's": "uáts",
    // Common adjectives
    "able": "êi-bul", "afraid": "ê-frêid", "angry": "án-gri", "anxious": "ánk-shes",
    "bad": "bad", "beautiful": "biú-ti-ful", "big": "big", "boring": "bór-in",
    "brave": "brêiv", "busy": "bíz-i", "careful": "kêr-ful", "cheap": "tchíp",
    "clean": "klín", "clever": "klêv-er", "cold": "kould", "comfortable": "kámf-ter-bul",
    "crazy": "krêi-zi", "cute": "kiút", "dangerous": "dêin-djer-es",
    "delicious": "di-lísh-es", "difficult": "díf-i-kult", "dirty": "dêr-ti",
    "dry": "drái", "dull": "dal", "easy": "íz-i", "empty": "êmp-ti",
    "expensive": "ik-spên-siv", "famous": "fêi-mes", "fast": "fast",
    "fat": "fat", "fine": "fáin", "funny": "fán-i", "glad": "glad",
    "good": "gud", "great": "grêit", "hard": "hard", "healthy": "hêl-di",
    "heavy": "hêv-i", "hot": "hat", "huge": "hiúdj", "hungry": "hán-gri",
    "interesting": "ín-ter-êst-in", "kind": "káind", "lazy": "lêi-zi",
    "long": "lon", "loud": "láud", "lovely": "láv-li", "lucky": "lák-i",
    "modern": "mód-ern", "neat": "nít", "new": "niú", "noisy": "nói-zi",
    "old": "ould", "perfect": "pêr-fekt", "poor": "pur", "pretty": "prít-i",
    "proud": "práud", "quiet": "kuái-et", "rich": "rítch", "sad": "sad",
    "safe": "sêif", "serious": "sír-i-es", "sharp": "sharp", "short": "short",
    "shy": "shái", "sick": "sik", "slow": "slou", "soft": "soft",
    "special": "spêsh-el", "strange": "strêindj", "strong": "stron",
    "stupid": "stiú-pid", "sweet": "suít", "tall": "tol", "terrible": "têr-i-bul",
    "thin": "din", "tired": "táierd", "ugly": "ág-li", "warm": "uorm",
    "weak": "uík", "weird": "uírd", "wet": "uêt", "wise": "uáiz",
    "wonderful": "uán-der-ful", "wrong": "ron", "young": "yáng",
    // Common verbs
    "answer": "án-ser", "arrive": "ê-ráiv", "ask": "ask", "bake": "bêik",
    "become": "bi-kám", "break": "brêik", "build": "bild", "buy": "bái",
    "catch": "kátch", "change": "tchêindj", "choose": "tchúz", "clean": "klín",
    "climb": "kláim", "close": "klouz", "cook": "kuk", "count": "káunt",
    "cut": "kat", "dance": "dans", "decide": "di-sáid", "draw": "dro",
    "drink": "drink", "drive": "dráiv", "drop": "drop", "eat": "ít",
    "enjoy": "in-djói", "explain": "ik-splêin", "fall": "fol", "feel": "fíl",
    "fight": "fáit", "find": "fáind", "fix": "fiks", "fly": "flái",
    "forget": "for-guêt", "get": "guêt", "give": "guív", "go": "gou",
    "grow": "grou", "happen": "háp-en", "hate": "hêit", "have": "hav",
    "hear": "hír", "help": "hêlp", "hit": "hit", "hold": "hould",
    "hope": "houp", "hurt": "hêrt", "keep": "kíp", "kill": "kil",
    "know": "nou", "laugh": "laf", "learn": "lêrn", "leave": "lív",
    "let": "lêt", "live": "lív", "look": "luk", "lose": "lúz",
    "love": "lav", "make": "mêik", "mean": "mín", "meet": "mít",
    "move": "múv", "need": "níd", "open": "óu-pen", "pay": "pêi",
    "play": "plêi", "pull": "pul", "push": "push", "put": "put",
    "reach": "rítch", "read": "ríd", "receive": "ri-sív", "remember": "ri-mêm-ber",
    "return": "ri-têrn", "run": "ran", "say": "sêi", "see": "sí",
    "seem": "sím", "sell": "sêl", "send": "sênd", "show": "shou",
    "sing": "sin", "sit": "sit", "sleep": "slíp", "speak": "spík",
    "start": "start", "stop": "stop", "study": "stád-i", "swim": "suím",
    "take": "têik", "talk": "tok", "teach": "títch", "tell": "têl",
    "think": "dink", "throw": "drou", "travel": "tráv-el", "try": "trái",
    "turn": "têrn", "understand": "ân-der-stánd", "use": "iúz", "visit": "víz-it",
    "wait": "uêit", "walk": "uok", "want": "uánt", "watch": "uótch",
    "win": "uín", "wish": "uísh", "work": "uêrk", "worry": "uêr-i",
    "write": "ráit",
    // Numbers
    "one": "uán", "two": "tú", "three": "drí", "four": "for",
    "five": "fáiv", "six": "siks", "seven": "sêv-en", "eight": "êit",
    "nine": "náin", "ten": "tên", "eleven": "i-lêv-en", "twelve": "tuêlv",
    "thirteen": "dêr-tín", "fourteen": "for-tín", "fifteen": "fif-tín",
    "sixteen": "siks-tín", "seventeen": "sêv-en-tín", "eighteen": "êit-tín",
    "nineteen": "náin-tín", "twenty": "tuên-ti", "thirty": "dêr-ti",
    "forty": "for-ti", "fifty": "fíf-ti", "sixty": "síks-ti",
    "seventy": "sêv-en-ti", "eighty": "êit-i", "ninety": "náin-ti",
    "hundred": "hán-dred", "thousand": "dáuz-end", "million": "míl-yen",
    // Days/Months
    "monday": "mán-dêi", "tuesday": "tiúz-dêi", "wednesday": "uênz-dêi",
    "thursday": "dêrz-dêi", "friday": "frái-dêi", "saturday": "sát-er-dêi",
    "sunday": "sán-dêi", "january": "dján-iu-êri", "february": "fêb-riu-êri",
    "march": "martch", "april": "êi-prel", "may": "mêi", "june": "djún",
    "july": "dju-lái", "august": "ó-gust", "september": "sêp-têm-ber",
    "october": "ak-tóu-ber", "november": "nou-vêm-ber", "december": "di-sêm-ber",
    // Food & Common Nouns
    "apple": "áp-ul", "banana": "bê-nán-ê", "bread": "brêd", "breakfast": "brêk-fest",
    "butter": "bát-er", "cake": "kêik", "cheese": "tchíz", "chicken": "tchík-en",
    "coffee": "kóf-i", "cookie": "kúk-i", "dinner": "dín-er", "egg": "êg",
    "fish": "fish", "fruit": "frút", "juice": "djús", "lunch": "lantch",
    "meat": "mít", "milk": "milk", "orange": "ór-indj", "pasta": "pást-ê",
    "pizza": "pít-sê", "potato": "po-têi-tou", "rice": "ráis", "salad": "sál-ed",
    "sandwich": "sánd-uitch", "sugar": "shúg-er", "tea": "tí", "tomato": "tê-mêi-tou",
    "vegetable": "vêdj-tê-bul", "water": "uót-er",
    // Body
    "arm": "árm", "back": "bak", "body": "bód-i", "bone": "boun",
    "brain": "brêin", "chest": "tchêst", "ear": "ír", "eye": "ái",
    "face": "fêis", "finger": "fín-ger", "foot": "fut", "hair": "hêr",
    "hand": "hand", "head": "hêd", "heart": "hárt", "knee": "ní",
    "leg": "lêg", "lip": "lip", "mouth": "máud", "neck": "nêk",
    "nose": "nouz", "shoulder": "shóul-der", "skin": "skin", "stomach": "stám-ek",
    "throat": "drout", "tooth": "túd", "wrist": "rist",
    // Places
    "airport": "êr-port", "bank": "bank", "bathroom": "bád-rúm", "beach": "bítch",
    "bedroom": "bêd-rúm", "bridge": "bridj", "building": "bíld-in", "church": "tchêrtch",
    "city": "sít-i", "college": "kól-idj", "country": "kán-tri", "downtown": "dáun-taun",
    "farm": "farm", "forest": "fór-est", "garden": "gár-den", "gym": "djim",
    "highway": "hái-uêi", "hospital": "hós-pi-tel", "hotel": "hou-têl",
    "island": "ái-lend", "kitchen": "kítch-en", "library": "lái-brêr-i",
    "market": "már-ket", "mountain": "máun-ten", "museum": "miú-zí-em",
    "neighborhood": "nêi-ber-hud", "office": "óf-is", "park": "park",
    "pharmacy": "fár-mê-si", "pool": "púl", "restaurant": "rês-tê-rant",
    "road": "roud", "school": "skúl", "shop": "shop", "street": "strít",
    "supermarket": "súper-már-ket", "university": "iú-ni-vêr-si-ti", "zoo": "zú",
};
